package com.ksy.view;

import com.model.MemberDAO;
import com.model.MemberService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kcat2
 */
public class PostGUI extends javax.swing.JFrame implements ActionListener {

    private MemberDAO memberDao;

    public PostGUI() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btReg = new javax.swing.JButton();
        btMemEdit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btRes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Postbox");

        btReg.setBackground(new java.awt.Color(0, 111, 62));
        btReg.setFont(new java.awt.Font("맑은 고딕", 1, 32)); // NOI18N
        btReg.setForeground(new java.awt.Color(255, 255, 255));
        btReg.setText("택배접수");
        btReg.setAlignmentY(0.0F);
        btReg.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btReg.setIconTextGap(0);
        btReg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegActionPerformed(evt);
            }
        });

        btMemEdit.setBackground(new java.awt.Color(254, 254, 254));
        btMemEdit.setFont(new java.awt.Font("맑은 고딕", 1, 32)); // NOI18N
        btMemEdit.setForeground(new java.awt.Color(0, 111, 62));
        btMemEdit.setText("회원정보수정");
        btMemEdit.setAlignmentY(0.0F);
        btMemEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btMemEdit.setBorderPainted(false);
        btMemEdit.setFocusPainted(false);
        btMemEdit.setIconTextGap(0);
        btMemEdit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btMemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemEditActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 62)));

        tfUser.setEditable(false);
        tfUser.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        jLabel4.setText("님 환영합니다");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btList.setBackground(new java.awt.Color(254, 254, 254));
        btList.setFont(new java.awt.Font("맑은 고딕", 1, 32)); // NOI18N
        btList.setForeground(new java.awt.Color(0, 111, 62));
        btList.setText("예약현황");
        btList.setAlignmentY(0.0F);
        btList.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btList.setBorderPainted(false);
        btList.setFocusPainted(false);
        btList.setIconTextGap(0);
        btList.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\lecture\\workspace_list\\nb_ws\\postbox\\src\\main\\java\\img\\logo.png")); // NOI18N

        btRes.setBackground(new java.awt.Color(12, 196, 180));
        btRes.setFont(new java.awt.Font("맑은 고딕", 1, 32)); // NOI18N
        btRes.setForeground(new java.awt.Color(255, 255, 255));
        btRes.setText("택배예약");
        btRes.setAlignmentY(0.0F);
        btRes.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btRes.setIconTextGap(0);
        btRes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btList, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btRes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btReg, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btList, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegActionPerformed

    private void btMemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMemEditActionPerformed

    private void btResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btResActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btList;
    private javax.swing.JButton btMemEdit;
    private javax.swing.JButton btReg;
    private javax.swing.JButton btRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables

    private void init() {
        tfUser.setText(MemberService.getId());
        addEvent();
    }

    private void addEvent() {
        btMemEdit.addActionListener(this); //회원정보수정
        btList.addActionListener(this); //예약현황
        btRes.addActionListener(this);  //택배예약
        btReg.addActionListener(this);  //택배접수
    }

    @Override
    public void actionPerformed(ActionEvent e) {

        if (e.getSource() == btList) {

            try {
                ReserveListGUI f = new ReserveListGUI();
                f.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PostGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (e.getSource() == btMemEdit) {
            
                PwdGUI f=new PwdGUI();
                f.setVisible(true);
                /*
                try {
                JoinGUI f = new JoinGUI(JoinGUI.MEMBER_EDIT);
                f.setVisible(true);
                } catch (SQLException ex) {
                Logger.getLogger(PostGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                */
            
        } else if (e.getSource() == btRes) {

            try {
                ReserveGUI f = new ReserveGUI(ReserveGUI.RES);
                f.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PostGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (e.getSource() == btReg) {
            RegisterGUI f;
            try {
                f = new RegisterGUI();
                f.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PostGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
}
