/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ksy.view;

import com.model.ReceiverDAO;
import com.model.ReceiverDTO;
import com.model.ResDAO;
import com.model.ResDTO;
import com.model.SenderDAO;
import com.model.SenderDTO;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegisterGUI extends javax.swing.JFrame implements ActionListener {

    private String colNames[] = {"예약번호", "예약명", "예약일"};
    private DefaultTableModel model = new DefaultTableModel();
    private ResDAO resdao = new ResDAO();
    private SenderDAO sdao = new SenderDAO();
    private ReceiverDAO rdao = new ReceiverDAO();
    private int resno;

    public RegisterGUI() throws SQLException {
        initComponents();
        init();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pSender = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfSname = new javax.swing.JTextField();
        tfShp = new javax.swing.JTextField();
        tfSaddr = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfRname = new javax.swing.JTextField();
        tfRaddr = new javax.swing.JTextField();
        tfpay = new javax.swing.JTextField();
        btWeight = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfFare = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        restable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tfWeight = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btReg = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("택배접수");

        jLabel1.setFont(new java.awt.Font("휴먼둥근헤드라인", 0, 36)); // NOI18N
        jLabel1.setText("예약내역 확인 및 선택");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "예약세부내역 확인", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 1, 20))); // NOI18N

        pSender.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)), "보내는 사람", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 0, 17))); // NOI18N

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        jLabel2.setText("성명");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        jLabel3.setText("연락처");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        jLabel4.setText("주소");

        tfSname.setEditable(false);
        tfSname.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        tfSname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSnameActionPerformed(evt);
            }
        });

        tfShp.setEditable(false);
        tfShp.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N

        tfSaddr.setEditable(false);
        tfSaddr.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N

        javax.swing.GroupLayout pSenderLayout = new javax.swing.GroupLayout(pSender);
        pSender.setLayout(pSenderLayout);
        pSenderLayout.setHorizontalGroup(
            pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSenderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfShp, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(tfSname)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pSenderLayout.setVerticalGroup(
            pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSenderLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfShp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pSenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)), "받는 사람", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 0, 17))); // NOI18N
        jPanel3.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        jLabel5.setText("성명");

        jLabel6.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        jLabel6.setText("지불방법");

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        jLabel7.setText("주소");

        tfRname.setEditable(false);
        tfRname.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        tfRname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRnameActionPerformed(evt);
            }
        });

        tfRaddr.setEditable(false);
        tfRaddr.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N

        tfpay.setEditable(false);
        tfpay.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tfpay, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfRname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pSender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pSender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        btWeight.setBackground(new java.awt.Color(0, 111, 62));
        btWeight.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        btWeight.setForeground(new java.awt.Color(255, 255, 255));
        btWeight.setText("무게 측정");

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        jLabel8.setText("합계");

        tfFare.setEditable(false);
        tfFare.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N

        restable.setFont(new java.awt.Font("맑은 고딕", 0, 17)); // NOI18N
        restable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        restable.setRowHeight(30);
        jScrollPane2.setViewportView(restable);
        if (restable.getColumnModel().getColumnCount() > 0) {
            restable.getColumnModel().getColumn(0).setResizable(false);
            restable.getColumnModel().getColumn(1).setResizable(false);
            restable.getColumnModel().getColumn(2).setResizable(false);
            restable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        jLabel9.setText("무게");

        tfWeight.setEditable(false);
        tfWeight.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btReg.setBackground(new java.awt.Color(0, 111, 62));
        btReg.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        btReg.setForeground(new java.awt.Color(255, 255, 255));
        btReg.setText("택배 접수하기");
        btReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegActionPerformed(evt);
            }
        });
        jPanel1.add(btReg);

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        jLabel10.setText("g");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tfFare, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btWeight))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfFare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSnameActionPerformed

    private void tfRnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRnameActionPerformed

    private void btRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisterGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReg;
    private javax.swing.JButton btWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pSender;
    private javax.swing.JTable restable;
    public javax.swing.JTextField tfFare;
    private javax.swing.JTextField tfRaddr;
    private javax.swing.JTextField tfRname;
    private javax.swing.JTextField tfSaddr;
    private javax.swing.JTextField tfShp;
    private javax.swing.JTextField tfSname;
    public javax.swing.JTextField tfWeight;
    private javax.swing.JTextField tfpay;
    // End of variables declaration//GEN-END:variables

    private void init() throws SQLException {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        showList();
    }

    private void addEvent() {
        restable.addMouseListener(new EventHandler());
        btWeight.addActionListener(this);
        btReg.addActionListener(this);
    }

    public void showList() throws SQLException {
        List<ResDTO> list = resdao.getReslist();
        String[][] data = new String[list.size()][colNames.length];

        for (int i = 0; i < list.size(); i++) {
            ResDTO dto = list.get(i);

            data[i][0] = Integer.toString(dto.getResNo());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd");
            String resdate = sdf.format(dto.getResDate());
            data[i][1] = dto.getResAlias();
            data[i][2] = resdate;

        }
        model.setDataVector(data, colNames);
        restable.setModel(model);

        //tableheader설정
        restable.getTableHeader().setFont(new Font("맑은 고딕", Font.BOLD, 18));

        //각 칼럼 사이즈 조절
        restable.getColumnModel().getColumn(0).setPreferredWidth(100);
        restable.getColumnModel().getColumn(1).setPreferredWidth(300);
        restable.getColumnModel().getColumn(2).setPreferredWidth(200);

        restable.setRowHeight(22);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(resno==0){
                    JOptionPane.showMessageDialog(this, "접수할 택배 예약을 선택하세요");
                    return;
                }
        if (e.getSource() == btWeight) {
           
            WeightGUI f = new WeightGUI(this);
            f.setVisible(true);
        }
        if (e.getSource() == btReg) {
            
           
            if(tfWeight.getText()==null || tfWeight.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "무게를 측정하세요");
            }
            
            int weight = Integer.parseInt(tfWeight.getText());
            int fare = Integer.parseInt(tfFare.getText());
            
            String msg = "";

            try {
                int cnt = resdao.completeReg(weight, fare, resno);

                if (cnt > 0) {
                    msg = "택배 접수 완료\n송장번호: "+resdao.getinvoiceNo(resno);
                    
                } else {
                    msg = "택배 접수 실패";
                    return;
                }

            } catch (SQLException ex) {
                Logger.getLogger(RegisterGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, msg);
            this.dispose();
        }
    }

    class EventHandler extends MouseAdapter {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getSource() == restable) {
                int row = restable.getSelectedRow();
                resno = Integer.parseInt((String) restable.getValueAt(row, 0));
                try {
                    SenderDTO sdto = sdao.selectByResno(resno);
                    ReceiverDTO rdto = rdao.selectByResno(resno);

                    //보내는사람 성명, 연락처, 주소
                    tfSname.setText(sdto.getSenderName());
                    tfShp.setText(sdto.getSenderHp());

                    String saddr1 = sdto.getAddress1();
                    String saddr2 = sdto.getAddress2();
                    String saddress = saddr1;

                    if (saddr2 != null && !saddr2.isEmpty()) {
                        saddress += saddr2;
                    }
                    tfSaddr.setText(saddress);

                    //받는 성명, 주소, 지불방법
                    tfRname.setText(rdto.getReceiverName());
                    tfpay.setText(rdto.getPayment());

                    String raddr1 = rdto.getAddress1();
                    String raddr2 = rdto.getAddress2();
                    String raddress = raddr1;

                    if (raddr2 != null && !raddr2.isEmpty()) {
                        raddress += raddr2;
                    }
                    tfRaddr.setText(raddress);

                } catch (SQLException ex) {
                    Logger.getLogger(RegisterGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }
}
