/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ksy.view;

import com.model.MemberDAO;
import com.model.MemberDTO;
import com.model.MemberService;
import com.model.ReceiverDAO;
import com.model.ReceiverDTO;
import com.model.ResDAO;
import com.model.ResDTO;
import com.model.SenderDAO;
import com.model.SenderDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kcat2
 */
public class ReserveGUI extends javax.swing.JFrame implements ActionListener {

    private ResDAO resdao = new ResDAO();
    private SenderDAO sdrdao = new SenderDAO();
    private ReceiverDAO rcvdao = new ReceiverDAO();
    private ReserveListGUI gui;
    private int resFlag;    //예약인지, 예약 수정인지 구분해주는 값
    public static final int RES_EDIT = 1; //예약 수정
    public static final int RES = 2;      //택배 예약

    private int resno;

    public ReserveGUI() throws SQLException {
        initComponents();
        init();
        addEvent();
    }

    public ReserveGUI(int resFlag, int resno) throws SQLException {
        this();
        this.resFlag = resFlag;
        this.resno = resno;
        reserveEdit();
        
    }

    public ReserveGUI(ReserveListGUI gui, int resFlag, int resno) throws SQLException {
        this();
        this.resFlag = resFlag;
        this.resno = resno;
        this.gui=gui;
        reserveEdit();
        
    }

    public ReserveGUI(int resFlag) throws SQLException {
        this();
        this.resFlag = resFlag;
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tfAlias = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btRes = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfSname = new javax.swing.JTextField();
        btZipcode1 = new javax.swing.JButton();
        tfSaddr2 = new javax.swing.JTextField();
        tfSzipcode = new javax.swing.JTextField();
        tfSaddr1 = new javax.swing.JTextField();
        tfShp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btZipcode2 = new javax.swing.JButton();
        tfRZipcode = new javax.swing.JTextField();
        Cbpay = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfRaddr2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfRaddr1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfRhp = new javax.swing.JTextField();
        tfRname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfMsg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("택배예약");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        jLabel2.setText("물품정보");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        tfAlias.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        tfAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAliasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("* 등록 명칭을 입력해주세요. (예: 친구 선물)");

        jLabel12.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("↑ 보내는분 정보");

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btRes.setBackground(new java.awt.Color(0, 111, 62));
        btRes.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        btRes.setForeground(new java.awt.Color(255, 255, 255));
        btRes.setText("택배 예약하기");
        jPanel3.add(btRes);

        btCancel.setBackground(new java.awt.Color(254, 254, 254));
        btCancel.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        btCancel.setText("취소");
        jPanel3.add(btCancel);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel3.setText("이름");

        tfSname.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N

        btZipcode1.setBackground(new java.awt.Color(0, 111, 62));
        btZipcode1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        btZipcode1.setForeground(new java.awt.Color(255, 255, 255));
        btZipcode1.setText("주소검색");

        tfSaddr2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N

        tfSzipcode.setEditable(false);
        tfSzipcode.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        tfSzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSzipcodeActionPerformed(evt);
            }
        });

        tfSaddr1.setEditable(false);
        tfSaddr1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N

        tfShp.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        tfShp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfShpActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel9.setText("상세주소");

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel7.setText("주소");

        jLabel6.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel6.setText("우편번호");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel4.setText("연락처");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfSzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btZipcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfSaddr2)
                                .addComponent(tfSaddr1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfShp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSname, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfShp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btZipcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSaddr1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSaddr2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        btZipcode2.setBackground(new java.awt.Color(0, 111, 62));
        btZipcode2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        btZipcode2.setForeground(new java.awt.Color(255, 255, 255));
        btZipcode2.setText("주소검색");

        tfRZipcode.setEditable(false);
        tfRZipcode.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N

        Cbpay.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        Cbpay.setMaximumRowCount(2);
        Cbpay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "선불", "착불" }));

        jLabel17.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel17.setText("배송요청사항");

        jLabel16.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel16.setText("상세주소");

        tfRaddr2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel15.setText("연락처");

        tfRaddr1.setEditable(false);
        tfRaddr1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel5.setText("이름");

        tfRhp.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        tfRhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRhpActionPerformed(evt);
            }
        });

        tfRname.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel13.setText("지불방법");

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel10.setText("주소");

        tfMsg.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        tfMsg.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel8.setText("우편번호");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel16))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(tfRZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btZipcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfRaddr2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                .addComponent(tfRaddr1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRname, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRhp, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Cbpay, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 36, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfRname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfRhp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfRZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btZipcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfRaddr1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRaddr2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cbpay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("↓ 받는분 정보");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addComponent(tfAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(tfAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfShpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfShpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfShpActionPerformed

    private void tfAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAliasActionPerformed

    private void tfRhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRhpActionPerformed

    private void tfSzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSzipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSzipcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReserveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReserveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReserveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReserveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReserveGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ReserveGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbpay;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btRes;
    public javax.swing.JButton btZipcode1;
    public javax.swing.JButton btZipcode2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfAlias;
    private javax.swing.JTextField tfMsg;
    public javax.swing.JTextField tfRZipcode;
    public javax.swing.JTextField tfRaddr1;
    private javax.swing.JTextField tfRaddr2;
    private javax.swing.JTextField tfRhp;
    private javax.swing.JTextField tfRname;
    public javax.swing.JTextField tfSaddr1;
    private javax.swing.JTextField tfSaddr2;
    private javax.swing.JTextField tfShp;
    private javax.swing.JTextField tfSname;
    public javax.swing.JTextField tfSzipcode;
    // End of variables declaration//GEN-END:variables

    private void init() throws SQLException {
        MemberDAO mdao = new MemberDAO();
        MemberDTO mdto = mdao.getInfo();

        tfSname.setText(mdto.getName());
        tfShp.setText(mdto.getHp());
        tfSzipcode.setText(mdto.getZipcode());
        tfSaddr1.setText(mdto.getAddress1());
        tfSaddr2.setText(mdto.getAddress2());

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void addEvent() {
        btRes.addActionListener(this);
        btCancel.addActionListener(this);
        btZipcode1.addActionListener(this);
        btZipcode2.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btRes) {
            try {
                if(resFlag==RES) 
                    reservation();
                else if(resFlag==RES_EDIT){
                    resEdit();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ReserveGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (e.getSource() == btZipcode1) {
            SubZipcode f = new SubZipcode(this, btZipcode1);
            f.setVisible(true);
        }

        if (e.getSource() == btZipcode2) {
            SubZipcode f = new SubZipcode(this, btZipcode2);
            f.setVisible(true);
        }
        if (e.getSource() == btCancel) {
            dispose();
        }

    }

    private void reservation() throws SQLException {
        String alias = tfAlias.getText();

        String sName = tfSname.getText();
        String sHp = tfShp.getText();
        String sZipcode = tfSzipcode.getText();
        String sAddress1 = tfSaddr1.getText();
        String sAddress2 = tfSaddr2.getText();

        //받는분
        String rName = tfRname.getText();
        String rHp = tfRhp.getText();
        String rZipcode = tfRZipcode.getText();
        String rAddress1 = tfRaddr1.getText();
        String rAddress2 = tfRaddr2.getText();

        String msg = tfMsg.getText();
        String pay = (String) Cbpay.getSelectedItem();

        if(checkData(alias, sName, sHp,sZipcode, rName, rHp, rZipcode, pay)<0)
            return;
        
        ResDTO resdto = new ResDTO();
        resdto.setResAlias(alias);
        resdto.setId(MemberService.getId());

        String result = "";
        int resno = resdao.getresNo();
        int cnt1 = resdao.insertRes(resdto, resno);

        //보내는분
        SenderDTO sendto = new SenderDTO();
        sendto.setSenderName(sName);
        sendto.setSenderHp(sHp);
        sendto.setZipcode(sZipcode);
        sendto.setAddress1(sAddress1);
        sendto.setAddress2(sAddress2);
        int cnt2 = sdrdao.insertSender(sendto, resno);

        ReceiverDTO recdto = new ReceiverDTO();
        recdto.setReceiverName(rName);
        recdto.setReceiverHp(rHp);
        recdto.setZipcode(rZipcode);
        recdto.setAddress1(rAddress1);
        recdto.setAddress2(rAddress2);

        recdto.setRequestMsg(msg);
        recdto.setPayment(pay);
        int cnt3 = rcvdao.insertReceiver(recdto, resno);

        if (cnt1 * cnt2 * cnt3 > 0) {
            result = "예약 성공";
            System.out.println("showList()");
            
        } else {
            result = "예약 실패";
        }

        JOptionPane.showMessageDialog(this, result);
        dispose();

    }

    private void reserveEdit() throws SQLException {
       
        if(resFlag==ReserveGUI.RES){
            setTitle("택배예약");
            btRes.setText("택배예약");
        }else if(resFlag==ReserveGUI.RES_EDIT){
            setTitle("택배예약수정");
            btRes.setText("예약수정");
            clearSender();
            showByResno();
        }
    
    }

    private void showByResno() throws SQLException {
        //예약번호로 조회해서 화면에 출력
       ResDTO resdto=resdao.selectByResno(resno);
       tfAlias.setText(resdto.getResAlias());
       
       //보내는 사람 정보 load
       SenderDTO sdto=sdrdao.selectByResno(resno);
       tfSname.setText(sdto.getSenderName());
       tfShp.setText(sdto.getSenderHp());
       tfSzipcode.setText(sdto.getZipcode());
       tfSaddr1.setText(sdto.getAddress1());
       tfSaddr2.setText(sdto.getAddress2());
       
       //받는 사람 정보 load
       ReceiverDTO rdto=rcvdao.selectByResno(resno);
       tfRname.setText(rdto.getReceiverName());
       tfRhp.setText(rdto.getReceiverHp());
       tfRZipcode.setText(rdto.getZipcode());
       tfRaddr1.setText(rdto.getAddress1());
       tfRaddr2.setText(rdto.getAddress2());
       tfMsg.setText(rdto.getRequestMsg());
       Cbpay.setSelectedItem(rdto.getPayment());
    }

    private void clearSender() {
        tfSname.setText("");
        tfShp.setText("");
        tfSzipcode.setText("");
        tfSaddr1.setText("");
        tfSaddr2.setText("");
        
    }

    private void resEdit() throws SQLException {
        //예약 수정
       String alias=tfAlias.getText();
       
       //보내는 사람 정보 get
       String sName=tfSname.getText();
       String sHp=tfShp.getText();
       String sZipcode=tfSzipcode.getText();
       String sAddr1=tfSaddr1.getText();
       String sAddr2=tfSaddr2.getText();
       
       //받는 사람 정보 get
       String rName=tfRname.getText();
       String rHp=tfRhp.getText();
       String rZipcode=tfRZipcode.getText();
       String rAddr1=tfRaddr1.getText();
       String rAddr2=tfRaddr2.getText();
       String msg=tfMsg.getText();
       String pay=(String) Cbpay.getSelectedItem();
      
       if(checkData(alias, sName, sHp,sZipcode, rName, rHp, rZipcode, pay)<0)
            return;
       
       int cnt1=resdao.updateRes(resno, alias);
       SenderDTO senderdto=new SenderDTO();
       senderdto.setSenderName(sName);
       senderdto.setSenderHp(sHp);
       senderdto.setZipcode(sZipcode);
       senderdto.setAddress1(sAddr1);
       senderdto.setAddress2(sAddr2);       
       
       int cnt2=sdrdao.updateSender(senderdto,resno);
       
       ReceiverDTO receiverdto=new ReceiverDTO();
       receiverdto.setReceiverName(rName);
       receiverdto.setReceiverHp(rHp);
       receiverdto.setZipcode(rZipcode);
       receiverdto.setAddress1(rAddr1);
       receiverdto.setAddress2(rAddr2);
       receiverdto.setRequestMsg(msg);
       receiverdto.setPayment(pay);
       int cnt3=rcvdao.updateReceiver(receiverdto,resno);
       
       String info="";
       if(cnt1*cnt2*cnt3>0){
           info="예약 수정 성공";
           gui.showList();
       }
       else
           info="예약 수정 실패";
       JOptionPane.showMessageDialog(this, info);
       this.dispose();
       
    
    }

    private int checkData(String alias, String sName, String sHp, String sZipcode, String rName, String rHp, String rZipcode, String pay) {
        if (alias == null || alias.isEmpty()) {
            JOptionPane.showMessageDialog(this, "물품정보를 입력하세요");
            tfAlias.requestFocus();
             return -1;
        }
        if (sName == null || sName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "보내는분 이름을 입력하세요");
            tfSname.requestFocus();
             return -1;
        }

        if (sHp == null || sHp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "보내는분 연락처를 입력하세요");
            tfShp.requestFocus();
             return -1;
        }
        if (sZipcode == null || sZipcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "보내는분 우편번호를 입력하세요");
            tfSzipcode.requestFocus();
             return -1;
        }

        if (rName == null || rName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "받는분 이름을 입력하세요");
            tfRname.requestFocus();
            return -1;
        }
        if (rHp == null || rHp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "받는분 연락처를 입력하세요");
            tfRhp.requestFocus();
            return -1;
        }
        if (rZipcode == null || rZipcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "받는분 우편번호를 입력하세요");
            tfRZipcode.requestFocus();
            return -1;
        }

        if (pay == null || pay.isEmpty()) {
            JOptionPane.showMessageDialog(this, "지불방법을 선택하세요");
            Cbpay.requestFocus();
            return -1;
        }
        return 0;
    }
}
